version: "3.7"
services:
  traefik:
    image: "traefik:v2.4"
    restart: unless-stopped
    container_name: "traefik"
    security_opt:
      - no-new-privileges:true
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  client:
    container_name: learnup_react
    image: learnup_react:dev
    restart: always
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./client:/app
      - /app/node_modules/
    labels:
      - traefik.http.routers.client.rule=Host(`client.143.198.100.17`)
      - traefik.http.routers.client.tls=true
      - traefik.http.routers.client.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web
  mongo:
    container_name: learnup_mongo
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=sSqZ9B3E8aL4
      - MONGODB_INITDB_DATABASE=Users
    ports:
      - 27017:27017
    networks:
      - internal
    labels:
      - traefik.enable=false
    # volumes:
    #   - mongodb-data:/data/db
  redis:
    container_name: learnup_redis
    image: "redis:latest"
    command: redis-server --requirepass t8Hpb5TzPv5Q
    ports:
      - 6379:6379
    networks:
      - internal
    labels:
      - traefik.enable=false
  user:
    container_name: learnup_user
    image: learnup_user:dev
    restart: always
    build:
      context: ./API/UserMicroservice
      dockerfile: ./Dockerfile
    environment:
      - PUBLICH_PATH=143.110.155.94
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./API/UserMicroservice:/usr/src/app
      - /usr/src/app/node_modules/
    labels:
      - traefik.http.routers.user.rule=Host(`api.simple..143.198.100.17`)
      - traefik.http.routers.user.tls=true
      - traefik.http.routers.user.tls.certresolver=lets-encrypt
      - traefik.port=5000
    networks:
      - internal
      - web
    depends_on:
      - mysql
  postgres:
    container_name: learnup_postgres
    image: "postgres"
    environment:
      - POSTGRES_USER=learnup_user
      - POSTGRES_PASSWORD=qdDv5RPyYSgS
      - POSTGRES_DB=Learnup
    ports:
      - "5432:5432"
    networks:
      - internal
    labels:
      - traefik.enable=false
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data/
  whiteboard:
    container_name: learnup_whiteboard
    image: learnup_whiteboard:dev
    restart: always
    build:
      context: ./API/WhiteboardMicroservice
      dockerfile: ./Dockerfile
    environment:
      - PUBLICH_PATH=143.110.155.94
    depends_on:
      - postgres
    ports:
      - "5001:5001"
    volumes:
      - ./API/WhiteboardMicroservice:/usr/src/app
      - /usr/src/app/node_modules/
    labels:
      - traefik.http.routers.whiteboard.rule=Host(`api.simple..143.198.100.17`)
      - traefik.http.routers.whiteboard.tls=true
      - traefik.http.routers.whiteboard.tls.certresolver=lets-encrypt
      - traefik.port=5001
    networks:
      - internal
      - web
  audio:
    container_name: learnup_audio
    image: learnup_audio:dev
    restart: always
    environment:
      - PUBLICH_PATH=143.110.155.94
    build:
      context: ./API/audioMicroservice
      dockerfile: ./Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./API/audioMicroservice:/usr/src/app
      - /usr/src/app/node_modules/
    labels:
      - traefik.http.routers.audio.rule=Host(`api.simple..143.198.100.17`)
      - traefik.http.routers.audio.tls=true
      - traefik.http.routers.audio.tls.certresolver=lets-encrypt
      - traefik.port=5002
    networks:
      - internal
      - web
  signalling:
    container_name: learnup_webrtc_signalling
    image: learnup_webrtc_signalling:dev
    restart: always
    build:
      context: ./API/signallingServer
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./API/signallingServer:/user/src/app
      - /usr/src/app/node_modules/
    labels:
      - traefik.http.routers.signalling.rule=Host(`api.simple..143.198.100.17`)
      - traefik.http.routers.signalling.tls=true
      - traefik.http.routers.signalling.tls.certresolver=lets-encrypt
      - traefik.port=8081
    networks:
      - internal
      - web
    # volumes:
    #   postgres-data:
    #   mongodb-data:

    networks:
      web:
        external: true
      internal:
        external: true
