version: "3.9"
services:
  client:
    container_name: learnup_react
    image: learnup_react:dev
    restart: always
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true
  user:
    container_name: learnup_user
    image: learnup_user:dev
    restart: always
    build:
      context: ./API/UserMicroservice
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./API/UserMicroservice:/usr/src/app
      - /usr/src/app/node_modules/
  whiteboard:
    container_name: learnup_whiteboard
    image: learnup_whiteboard:dev
    restart: always
    build:
      context: ./API/WhiteboardMicroservice
      dockerfile: ./Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./API/WhiteboardMicroservice:/usr/src/app
      - /usr/src/app/node_modules/
  audio:
    container_name: learnup_audio
    image: learnup_audio:dev
    restart: always
    build:
      context: ./API/AudioMicroservice
      dockerfile: ./Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./API/AudioMicroservice:/usr/src/app
      - /usr/src/app/node_modules/
  signalling:
    container_name: learnup_webrtc_signalling
    image: learnup_webrtc_signalling:dev
    restart: always
    build:
      context: ./API/signallingServer
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./API/signallingServer:/user/src/app
      - /usr/src/app/node_modules/
