version: "3.9"
services:
  client:
    container_name: learnup_react
    image: learnup_react:dev
    restart: always
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true
  mongo:
    container_name: learnup_mongo
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=sSqZ9B3E8aL4
      # - MONGODB_INITDB_DATABASE=Users
    ports:
      - 27017:27017
    # volumes:
    #   - mongodb-data:/data/db
  redis:
    container_name: learnup_redis
    image: "redis:latest"
    command: redis-server --requirepass t8Hpb5TzPv5Q
    ports:
      - 6379:6379
  user:
    container_name: learnup_user
    image: learnup_user:dev
    restart: always
    build:
      context: ./API/UserMicroservice
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
      - redis
    # environment:
      # - PUBLIC_PATH=https://beta.tileboard.sparkcode.io/
    ports:
      - "5000:5000"
    volumes:
      - ./API/UserMicroservice:/usr/src/app
      - /usr/src/app/node_modules/
  postgres:
    container_name: learnup_postgres
    image: "postgres"
    environment:
      - POSTGRES_USER=learnup_user
      - POSTGRES_PASSWORD=qdDv5RPyYSgS
      - POSTGRES_DB=Learnup
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data/
  whiteboard:
    container_name: learnup_whiteboard
    image: learnup_whiteboard:dev
    restart: always
    build:
      context: ./API/WhiteboardMicroservice
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - "5001:5001"
    volumes:
      - ./API/WhiteboardMicroservice:/usr/src/app
      - /usr/src/app/node_modules/
  audio:
    container_name: learnup_audio
    image: learnup_audio:dev
    restart: always
    build:
      context: ./API/AudioMicroservice
      dockerfile: ./Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./API/AudioMicroservice:/usr/src/app
      - /usr/src/app/node_modules/
  signalling:
    container_name: learnup_webrtc_signalling
    image: learnup_webrtc_signalling:dev
    restart: always
    build:
      context: ./API/signallingServer
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./API/signallingServer:/user/src/app
      - /usr/src/app/node_modules/
# volumes:
#   postgres-data:
#   mongodb-data:
