[http.middlewares.simpleAuth.basicAuth]
    users = [
        "admin:$apr1$R/eo9zLd$FZPB6dMiN6iwPYYH3oULw0"
    ]

[http.routers.api]
    rule = "Host(`monitor.phonics-learningboard.jarethrader.com`)"
    entrypoints = ["websecure"]
    middlewares = ["simpleAuth"]
    service = "api@internal"
    [http.routers.api.tls]
        certResolver = "letsencrypt"
    [http.routers.api.tls.domains]
        main = "phonics-learningboard.jarethrader.com"