[log]
    level = "DEBUG"

[entryPoints]
    [entryPoints.web]
         address = ":80"
        [entryPoints.web.http.redirections.entryPoint]
            to = "websecure"
            scheme = "https"

        [entryPoints.websecure]
            address = ":443"

[api]
    dashboard = true

[certificatesResolvers.letsencrypt.acme]
    email = "jarethrdev@gmail.com"
    storage = "/letsencrypt/acme.json"
    [certificatesResolvers.letsencrypt.acme.tlsChallenge]

[providers.docker]
    exposedByDefault = false
    network = "traefik-global-proxy"

[providers.file]
    filename = "traefik_dynamic.toml"