[http.middlewares.simpleAuth.basicAuth]
    users = [
        "admin:$apr1$R/eo9zLd$FZPB6dMiN6iwPYYH3oULw0"
    ]

[http.routers.api]
    rule = "Host(`monitor.143.198.100.17`)"
    entrypoints = ["websecure"]
    middlewares = ["simpleAuth"]
    service = "api@internal"
    [http.routers.api.tls]
        certResolver = "lets-encrypt"